[package]
name = "rusty_invaders"
version = "0.1.0"
edition = "2024"

[[bin]]
name = "invaders"
path = "src/main.rs"

[lib]
name = "libvaders"
path = "src/lib.rs"

[dependencies]
minifb = "0.28.0"
raqote = "0.8.5"
